const teamAsset = {
  'D-backs': {city: 'Arizona'},
  Braves: {city: 'Atlanta'},
  Orioles: {city: 'Baltimore'},
  'Red Sox': {city: 'Boston'},
  Cubs: {city: 'Chicago'},
  'White Sox': {city: 'Chicago'},
  Reds: {city: 'Cincinnati'},
  Indians: {city: 'Cleveland'},
  Rockies: {city: 'Colorado'},
  Tigers: {city: 'Detroit'},
  Astros: {city: 'Houston'},
  Royals: {city: 'Kansas City'},
  Angels: {city: 'Los Angeles'},
  Dodgers: {city: 'Los Angeles'},
  Marlins: {city: 'Miami'},
  Brewers: {city: 'Milwaukee'},
  Twins: {city: 'Minnesota'},
  Mets: {city: 'New York'},
  Yankees: {city: 'New York'},
  Athletics: {city: 'Oakland'},
  Phillies: {city: 'Philadelphia'},
  Pirates: {city: 'Pittsburgh'},
  Cardinals: {city: 'St. Louis'},
  Padres: {city: 'San Diego'},
  Giants: {city: 'San Francisco'},
  Mariners: {city: 'Seattle'},
  Rays: {city: 'Tampa Bay'},
  Rangers: {city: 'Texas'},
  'Blue Jays': {city: 'Toronto'},
  Nationals: {city: 'Washington'},
};
