const teamAsset = {
  'D-backs': {city:'Arizona', logo1:'./images/dbacks1.png', logo2:'./images/dbacks2.png'},
  Braves: {city:'Atlanta', logo1:'./images/braves1.png', logo2:'./images/braves2.png'},
  Orioles: {city:'Baltimore', logo1:'./images/orioles1.png', logo2:'./images/orioles2.png'},
  'Red Sox': {city:'Boston', logo1:'./images/redSox1.png', logo2:'./images/redSox2.png'},
  Cubs: {city:'Chicago', logo1:'./images/cubs1.png', logo2:'./images/cubs2.png'},
  'White Sox': {city:'Chicago', logo1:'./images/whiteSox1.png', logo2:'./images/whiteSox2.png'},
  Reds: {city:'Cincinnati', logo1:'./images/reds1.png', logo2:'./images/reds2.png'},
  Indians: {city:'Cleveland', logo1:'./images/indians1.png', logo2:'./images/indians2.png'},
  Rockies: {city:'Colorado', logo1:'./images/rockies1.png', logo2:'./images/rockies2.png'},
  Tigers: {city:'Detroit', logo1:'./images/tigers1.png', logo2:'./images/tigers2.png'},
  Astros: {city:'Houston', logo1:'./images/astros1.png', logo2:'./images/astros2.png'},
  Royals: {city:'Kansas City', logo1:'./images/royals1.png', logo2:'./images/royals2.png'},
  Angels: {city:'Los Angeles', logo1:'./images/angels1.png', logo2:'./images/angels2.png'},
  Dodgers: {city:'Los Angeles', logo1:'./images/dodgers1.png', logo2:'./images/dodgers2.png'},
  Marlins: {city:'Miami', logo1:'./images/marlins1.png', logo2:'./images/marlins2.png'},
  Brewers: {city:'Milwaukee', logo1:'./images/brewers1.png', logo2:'./images/brewers2.png'},
  Twins: {city:'Minnesota', logo1:'./images/twins1.png', logo2:'./images/twins2.png'},
  Mets: {city:'New York', logo1:'./images/mets1.png', logo2:'./images/mets2.png'},
  Yankees: {city:'New York', logo1:'./images/yankees1.png', logo2:'./images/yankees2.png'},
  Athletics: {city:'Oakland', logo1:'./images/as1.png', logo2:'./images/as2.png'},
  Phillies: {city:'Philadelphia', logo1:'./images/phillies1.png', logo2:'./images/phillies2.png'},
  Pirates: {city:'Pittsburgh', logo1:'./images/pirates1.png', logo2:'./images/pirates2.png'},
  Cardinals: {city:'St. Louis', logo1:'./images/cardinals1.png', logo2:'./images/cardinals2.png'},
  Padres: {city:'San Diego', logo1:'./images/padres1.png', logo2:'./images/padres2.png'},
  Giants: {city:'San Francisco', logo1:'./images/giants1.png', logo2:'./images/giants2.png'},
  Mariners: {city:'Seattle', logo1:'./images/mariners1.png', logo2:'./images/mariners2.png'},
  Rays: {city:'Tampa Bay', logo1:'./images/rays1.png', logo2:'./images/rays2.png'},
  Rangers: {city:'Texas', logo1:'./images/rangers1.png', logo2:'./images/rangers2.png'},
  'Blue Jays': {city:'Toronto', logo1:'./images/blueJays1.png', logo2:'./images/blueJays2.png'},
  Nationals: {city:'Washington', logo1:'./images/nationals1.png', logo2:'./images/nationals2.png'},
}
