const teamAsset = {
  'D-backs': {city:'Arizona', logo1:'./images/dbacks1.png', logo2:'./images/dbacks2.png', primary:'#424242',secondary:'#a8162b'},
  Braves: {city:'Atlanta', logo1:'./images/braves1.png', logo2:'./images/braves2.png', primary:'#082854',secondary:'#ba0e2d'},
  Orioles: {city:'Baltimore', logo1:'./images/orioles1.png', logo2:'./images/orioles2.png', primary:'#',secondary:'#'},
  'Red Sox': {city:'Boston', logo1:'./images/redSox1.png', logo2:'./images/redSox2.png', primary:'#082144',secondary:'#cb0729'},
  Cubs: {city:'Chicago', logo1:'./images/cubs1.png', logo2:'./images/cubs2.png', primary:'#cc092f',secondary:'#003479'},
  'White Sox': {city:'Chicago', logo1:'./images/whiteSox1.png', logo2:'./images/whiteSox2.png', primary:'#ffffff',secondary:'#040204'},
  Reds: {city:'Cincinnati', logo1:'./images/reds1.png', logo2:'./images/reds2.png', primary:'#ffffff',secondary:'#be0f34'},
  Indians: {city:'Cleveland', logo1:'./images/indians1.png', logo2:'./images/indians2.png', primary:'#',secondary:'#'},
  Rockies: {city:'Colorado', logo1:'./images/rockies1.png', logo2:'./images/rockies2.png', primary:'#380982',secondary:'#84888b'},
  Tigers: {city:'Detroit', logo1:'./images/tigers1.png', logo2:'./images/tigers2.png', primary:'#ff4819',secondary:'#002c76'},
  Astros: {city:'Houston', logo1:'./images/astros1.png', logo2:'./images/astros2.png', primary:'#e57200',secondary:'#002147'},
  Royals: {city:'Kansas City', logo1:'./images/royals1.png', logo2:'./images/royals2.png', primary:'#ffffff',secondary:'#002c74'},
  Angels: {city:'Los Angeles', logo1:'./images/angels1.png', logo2:'./images/angels2.png', primary:'#ae0731',secondary:'#092245'},
  Dodgers: {city:'Los Angeles', logo1:'./images/dodgers1.png', logo2:'./images/dodgers2.png', primary:'#fcfefc',secondary:'#042e6c'},
  Marlins: {city:'Miami', logo1:'./images/marlins1.png', logo2:'./images/marlins2.png', primary:'#000000',secondary:'#fd4239'},
  Brewers: {city:'Milwaukee', logo1:'./images/brewers1.png', logo2:'./images/brewers2.png', primary:'#162b48',secondary:'#8d744a'},
  Twins: {city:'Minnesota', logo1:'./images/twins1.png', logo2:'./images/twins2.png', primary:'#be0f34',secondary:'#002144'},
  Mets: {city:'New York', logo1:'./images/mets1.png', logo2:'./images/mets2.png', primary:'#002c74',secondary:'#ff4a00'},
  Yankees: {city:'New York', logo1:'./images/yankees1.png', logo2:'./images/yankees2.png', primary:'#ffffff',secondary:'#00338e'},
  Athletics: {city:'Oakland', logo1:'./images/as1.png', logo2:'./images/as2.png', primary:'#ffb70f',secondary:'#004438'},
  Phillies: {city:'Philadelphia', logo1:'./images/phillies1.png', logo2:'./images/phillies2.png', primary:'#04529c',secondary:'#d41244'},
  Pirates: {city:'Pittsburgh', logo1:'./images/pirates1.png', logo2:'./images/pirates2.png', primary:'#ffc912',secondary:'#2b2723'},
  Cardinals: {city:'St. Louis', logo1:'./images/cardinals1.png', logo2:'./images/cardinals2.png', primary:'#042a5c',secondary:'#e41a34'},
  Padres: {city:'San Diego', logo1:'./images/padres1.png', logo2:'./images/padres2.png', primary:'#ffffff',secondary:'#0e2346'},
  Giants: {city:'San Francisco', logo1:'./images/giants1.png', logo2:'./images/giants2.png', primary:'#ff4819',secondary:'#2a2723'},
  Mariners: {city:'Seattle', logo1:'./images/mariners1.png', logo2:'./images/mariners2.png', primary:'#00665b',secondary:'#002144'},
  Rays: {city:'Tampa Bay', logo1:'./images/rays1.png', logo2:'./images/rays2.png', primary:'#64b3e9',secondary:'#001e43'},
  Rangers: {city:'Texas', logo1:'./images/rangers1.png', logo2:'./images/rangers2.png', primary:'#ffffff',secondary:'#e80033'},
  'Blue Jays': {city:'Toronto', logo1:'./images/blueJays1.png', logo2:'./images/blueJays2.png', primary:'#ffffff',secondary:'#1a459d'},
  Nationals: {city:'Washington', logo1:'./images/nationals1.png', logo2:'./images/nationals2.png', primary:'#001d45',secondary:'#be0527'},
}
